application: messenger
version: 1-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /resources
  static_dir: resources

- url: .*
  script: app.app

libraries:
- name: webapp2
  version: "2.5.1"